name = "dramaplay-api"
compatibility_date = "2026-06-22"
compatibility_flags = ["nodejs_compat"]
main = "src/index.ts"

[vars]
ENVIRONMENT = "production"

[[routes]]
pattern = "api.dramaplay.my.id/*"
zone_name = "dramaplay.my.id"

[[triggers]]
crons = ["*/15 * * * *"]
